In [1]:
# Cell 1: Imports and configuration
import os
from pathlib import Path
import libsbml
from collections import Counter
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
%matplotlib inline

In [16]:
# Cell 2: Deep SBML structure exploration

def explore_sbml_structure(sbml_file):
    """
    Explore ALL possible locations where gene information might be stored in an SBML file.
    Returns a dictionary with findings from different sections.
    
    Parameters:
    -----------
    sbml_file : str
        Path to SBML file
    
    Returns:
    --------
    dict
        Dictionary containing all found structures and their counts
    """
    reader = libsbml.SBMLReader()
    document = reader.readSBML(sbml_file)
    
    model = document.getModel()
    if model is None:
        return {"error": "Could not parse model"}
    
    findings = {
        "model_id": model.getId() if model.isSetId() else "No ID",
        "model_name": model.getName() if model.isSetName() else "No name",
        "sbml_level": document.getLevel(),
        "sbml_version": document.getVersion(),
        "num_reactions": model.getNumReactions(),
        "num_species": model.getNumSpecies(),
        "num_compartments": model.getNumCompartments(),
    }
    
    # Check for FBC plugin and gene products
    try:
        fbc_plugin = model.getPlugin('fbc')
        if fbc_plugin:
            findings["fbc_plugin"] = True
            findings["num_gene_products"] = fbc_plugin.getNumGeneProducts()
            
            # Sample some gene product IDs
            sample_genes = []
            for i in range(min(5, fbc_plugin.getNumGeneProducts())):
                gp = fbc_plugin.getGeneProduct(i)
                sample_genes.append({
                    "id": gp.getId(),
                    "label": gp.getLabel() if gp.isSetLabel() else "No label",
                    "name": gp.getName() if gp.isSetName() else "No name"
                })
            findings["sample_gene_products"] = sample_genes
        else:
            findings["fbc_plugin"] = False
    except:
        findings["fbc_plugin"] = "Error accessing FBC"
    
    # Check reactions for gene associations
    gene_association_types = set()
    sample_associations = []
    
    for i in range(min(10, model.getNumReactions())):  # Check first 10 reactions
        reaction = model.getReaction(i)
        
        # Check FBC gene product association
        try:
            rxn_fbc = reaction.getPlugin('fbc')
            if rxn_fbc:
                gpa = rxn_fbc.getGeneProductAssociation()
                if gpa:
                    gene_association_types.add("FBC_GeneProductAssociation")
                    assoc = gpa.getAssociation()
                    if assoc:
                        sample_associations.append({
                            "reaction": reaction.getId(),
                            "type": "FBC_GPA",
                            "content": str(assoc.toInfix()) if hasattr(assoc, 'toInfix') else "Complex object"
                        })
        except:
            pass
        
        # Check notes
        notes = reaction.getNotesString()
        if notes and "gene" in notes.lower():
            gene_association_types.add("Notes_contains_gene")
            if len(sample_associations) < 3:
                sample_associations.append({
                    "reaction": reaction.getId(),
                    "type": "Notes",
                    "content": notes[:200]  # First 200 chars
                })
        
        # Check annotations
        annotation = reaction.getAnnotationString()
        if annotation and "gene" in annotation.lower():
            gene_association_types.add("Annotation_contains_gene")
            if len(sample_associations) < 3:
                sample_associations.append({
                    "reaction": reaction.getId(),
                    "type": "Annotation",
                    "content": annotation[:200]
                })
    
    findings["gene_association_types"] = list(gene_association_types)
    findings["sample_associations"] = sample_associations
    
    # Check for any plugins
    plugins = []
    try:
        for i in range(model.getNumPlugins()):
            plugin = model.getPlugin(i)
            plugins.append(plugin.getPackageName())
    except:
        pass
    findings["plugins"] = plugins
    
    return findings

print("✓ Exploration function defined")

✓ Exploration function defined

In [18]:
# Cell 3: Set path and explore ALL models

# CHANGE THIS PATH
base_path = Path("models/")

# Store all findings organized by method and organism
all_findings = {}

for method_folder in base_path.iterdir():
    if not method_folder.is_dir():
        continue
    
    method_name = method_folder.name
    all_findings[method_name] = {}
    
    print(f"\n{'='*80}")
    print(f"METHOD: {method_name}")
    print(f"{'='*80}")
    
    for sbml_file in method_folder.glob("*.xml"):
        organism = sbml_file.stem
        
        print(f"\n  Organism: {organism}")
        print(f"  File: {sbml_file.name}")
        print(f"  {'-'*76}")
        
        findings = explore_sbml_structure(str(sbml_file))
        all_findings[method_name][organism] = findings
        
        # Print key findings
        if "error" in findings:
            print(f"    ❌ {findings['error']}")
            continue
        
        print(f"    SBML Level {findings['sbml_level']}, Version {findings['sbml_version']}")
        print(f"    Reactions: {findings['num_reactions']}")
        print(f"    Species: {findings['num_species']}")
        print(f"    Plugins: {findings['plugins']}")
        print(f"    FBC Plugin: {findings['fbc_plugin']}")
        
        if findings.get('num_gene_products', 0) > 0:
            print(f"    ✓ Gene Products (FBC): {findings['num_gene_products']}")
            if findings.get('sample_gene_products'):
                print(f"      Sample IDs:")
                for gp in findings['sample_gene_products'][:3]:
                    print(f"        - {gp['id']} (label: {gp['label']})")
        else:
            print(f"    ✗ No FBC Gene Products found")
        
        if findings.get('gene_association_types'):
            print(f"    Gene Association Types Found: {findings['gene_association_types']}")
            if findings.get('sample_associations'):
                print(f"      Examples:")
                for assoc in findings['sample_associations'][:2]:
                    print(f"        [{assoc['type']}] {assoc['reaction']}")
                    print(f"          {assoc['content'][:100]}...")

print(f"\n{'='*80}")
print("✓ Exploration complete")

================================================================================
METHOD: carveMe
================================================================================

  Organism: E_siliculosus
  File: E_siliculosus.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1548
    Species: 1080
    Plugins: ['fbc']
    FBC Plugin: True
    ✓ Gene Products (FBC): 786
      Sample IDs:
        - G_CBJ27061_1 (label: G_CBJ27061_1)
        - G_CBN77946_1 (label: G_CBN77946_1)
        - G_CBN76757_1 (label: G_CBN76757_1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_24DECOAR
          G_CBJ27061_1...

  Organism: CHO
  File: CHO.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1163
    Species: 850
    Plugins: ['fbc']
    FBC Plugin: True
    ✓ Gene Products (FBC): 702
      Sample IDs:
        - G_EGW07470_1 (label: G_EGW07470_1)
        - G_EGW07730_1 (label: G_EGW07730_1)
        - G_EGW00123_1 (label: G_EGW00123_1)

  Organism: A_aegypti
  File: A_aegypti.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1087
    Species: 790
    Plugins: ['fbc']
    FBC Plugin: True
    ✓ Gene Products (FBC): 649
      Sample IDs:
        - G_XP_001649088_2 (label: G_XP_001649088_2)
        - G_XP_021696045_1 (label: G_XP_021696045_1)
        - G_XP_001662725_1 (label: G_XP_001662725_1)

================================================================================
METHOD: merlin
================================================================================

  Organism: E_siliculosus
  File: E_siliculosus.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 2
    Reactions: 3813
    Species: 4492
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1642
      Sample IDs:
        - G_Esi_0418_0003 (label: Esi_0418_0003)
        - G_CBN74931_1 (label: CBN74931_1)
        - G_CBN75524_1 (label: CBN75524_1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_R06945__cytop
          CBJ30233_1...
        [FBC_GPA] R_R00562__cytop
          CBN79046_1...

  Organism: CHO
  File: CHO.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 2
    Reactions: 6390
    Species: 5584
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 2807
      Sample IDs:
        - G_EGW02227_1 (label: EGW02227_1)
        - G_EGV96904_1 (label: EGV96904_1)
        - G_EGW01634_1 (label: EGW01634_1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_R02108__extr
          (EGV96608_1 or EGV96609_1)...
        [FBC_GPA] R_R11895__nucl
          (EGW13933_1 or EGV99751_1 or EGW05467_1 or EGW04365_1 or EGW08268_1 or EGV92142_1 or EGW01255_1 or E...

  Organism: A_aegypti
  File: A_aegypti.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 2
    Reactions: 4820
    Species: 4466
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 4306
      Sample IDs:
        - G_XP_021702256_1 (label: XP_021702256_1)
        - G_XP_021698884_1 (label: XP_021698884_1)
        - G_XP_021702715_1 (label: XP_021702715_1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_R02108__extr
          (XP_001663616_1 or XP_001652172_1 or XP_001653283_2 or XP_001652404_1 or XP_021711527_1 or XP_001653...
        [FBC_GPA] R_TO0000304_cytmem__cytmem
          (XP_021705410_1 or XP_021705409_1 or XP_021705408_1 or XP_001653426_2 or XP_021705411_1)...

================================================================================
METHOD: modelseed
================================================================================

  Organism: E_siliculosus
  File: E_siliculosus.xml
  ----------------------------------------------------------------------------
    SBML Level 2, Version 1
    Reactions: 1104
    Species: 1179
    Plugins: ['layout']
    FBC Plugin: False
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_rxn00001_c0
          <notes>
  <html:p>GENE_ASSOCIATION:((CBN78008.1 or CBN78155.1 or CBJ27682.1) or (CBJ25689.1 or CBN78...
        [Notes] R_rxn00001_d0
          <notes>
  <html:p>GENE_ASSOCIATION:(CBN78008.1 or CBN78155.1 or CBJ27682.1)</html:p>
  <html:p>PROTE...

  Organism: CHO
  File: CHO.xml
  ----------------------------------------------------------------------------
    SBML Level 2, Version 1
    Reactions: 1104
    Species: 1179
    Plugins: ['layout']
    FBC Plugin: False
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_rxn00001_c0
          <notes>
  <html:p>GENE_ASSOCIATION:(EGV93776.1 or (EGW03581.1 or EGW02191.1 or EGW14471.1 or EGV9383...
        [Notes] R_rxn00001_d0
          <notes>
  <html:p>GENE_ASSOCIATION:EGV93776.1</html:p>
  <html:p>PROTEIN_ASSOCIATION:EGV93776.1</htm...

  Organism: A_aegypti
  File: A_aegypti.xml
  ----------------------------------------------------------------------------
    SBML Level 2, Version 1
    Reactions: 1104
    Species: 1179
    Plugins: ['layout']
    FBC Plugin: False
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_rxn00001_c0
          <notes>
  <html:p>GENE_ASSOCIATION:Unknown</html:p>
  <html:p>PROTEIN_ASSOCIATION:Unknown</html:p>
<...
        [Notes] R_rxn00001_d0
          <notes>
  <html:p>GENE_ASSOCIATION:Unknown</html:p>
  <html:p>PROTEIN_ASSOCIATION:Unknown</html:p>
<...

================================================================================
METHOD: raven_homo
================================================================================

  Organism: E_siliculosus
  File: E_siliculosus.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1710
    Species: 1928
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1141
      Sample IDs:
        - CBJ48774__46__1 (label: CBJ48774__46__1)
        - CBJ30928__46__1 (label: CBJ30928__46__1)
        - CBN78444__46__1 (label: CBN78444__46__1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_R00009
          CBJ26817__46__1...
        [FBC_GPA] R_R00010
          (CBJ29799__46__1 or CBJ33981__46__1)...

  Organism: CHO
  File: CHO.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 2210
    Species: 2288
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1990
      Sample IDs:
        - EGW03289__46__1 (label: EGW03289__46__1)
        - EGW12439__46__1 (label: EGW12439__46__1)
        - EGW15111__46__1 (label: EGW15111__46__1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_R00006
          EGV95477__46__1...
        [FBC_GPA] R_R00009
          EGV94204__46__1...

  Organism: A_aegypti
  File: A_aegypti.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1723
    Species: 1897
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 3452
      Sample IDs:
        - XP_021705167__46__1 (label: XP_021705167__46__1)
        - XP_021706998__46__1 (label: XP_021706998__46__1)
        - XP_021706447__46__1 (label: XP_021706447__46__1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_R00006
          (XP_001660326__46__1 or XP_021712412__46__1)...
        [FBC_GPA] R_R00009
          (XP_001663600__46__1 or XP_011493719__46__1)...

================================================================================
METHOD: reconstructor
================================================================================

================================================================================
METHOD: old
================================================================================

================================================================================
METHOD: raven
================================================================================

  Organism: E_siliculosus
  File: E_siliculosus.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1322
    Species: 1789
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1428
      Sample IDs:
        - CBJ25464__46__1 (label: CBJ25464__46__1)
        - CBJ25471__46__1 (label: CBJ25471__46__1)
        - CBJ25483__46__1 (label: CBJ25483__46__1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_RXN__45__8042
          (CBJ27057__46__1 or CBJ28883__46__1 or CBJ31710__46__1)...
        [FBC_GPA] R_GPH__45__RXN
          (CBJ28195__46__1 or CBJ29025__46__1)...

  Organism: CHO
  File: CHO.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1756
    Species: 2127
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 2275
      Sample IDs:
        - EGV91281__46__1 (label: EGV91281__46__1)
        - EGV91340__46__1 (label: EGV91340__46__1)
        - EGV91370__46__1 (label: EGV91370__46__1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_GLYCOLATE__45__REDUCTASE__45__RXN
          (EGW00407__46__1 or EGW00864__46__1)...
        [FBC_GPA] R_DEOXYADENOSINE__45__KINASE__45__RXN
          (EGW00581__46__1 or EGW09957__46__1)...

  Organism: A_aegypti
  File: A_aegypti.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1365
    Species: 1753
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 3677
      Sample IDs:
        - XP_001647579__46__2 (label: XP_001647579__46__2)
        - XP_001647586__46__2 (label: XP_001647586__46__2)
        - XP_001647648__46__2 (label: XP_001647648__46__2)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_GLYCOLATE__45__REDUCTASE__45__RXN
          (XP_001650858__46__1 or XP_001650860__46__1 or XP_021693117__46__1 or XP_021693119__46__1 or XP_0216...
        [FBC_GPA] R_DEOXYADENOSINE__45__KINASE__45__RXN
          (XP_001657341__46__1 or XP_001657342__46__1)...

================================================================================
METHOD: AuReMe
================================================================================

  Organism: E_siliculosus
  File: E_siliculosus.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 3403
    Species: 3981
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_1__45__PHOSPHATIDYLINOSITOL__45__3__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (CBJ33367.1) or (CBN7...
        [Notes] R_1__45__PHOSPHATIDYLINOSITOL__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (CBN79112.1) or (CBN7...

  Organism: CHO
  File: CHO.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 6968
    Species: 6629
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_1__45__PHOSPHATIDYLINOSITOL__45__3__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (EGW11902.1) or (EGV9...
        [Notes] R_1__45__PHOSPHATIDYLINOSITOL__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (EGV99292.1) or (EGV9...

  Organism: A_aegypti
  File: A_aegypti.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1851
    Species: 2294
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_1__45__PHOSPHATIDYLINOSITOL__45__3__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (XP_021700783.1) or (...
        [Notes] R_1__45__PHOSPHATIDYLINOSITOL__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (XP_021695754.1) or (...

================================================================================
METHOD: raven_comb
================================================================================

  Organism: E_siliculosus
  File: E_siliculosus.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 2503
    Species: 3043
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1700
      Sample IDs:
        - CBJ25464__46__1 (label: CBJ25464__46__1)
        - CBJ25471__46__1 (label: CBJ25471__46__1)
        - CBJ25483__46__1 (label: CBJ25483__46__1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_RXN__45__8042
          (CBJ27057__46__1 or CBJ28883__46__1 or CBJ31710__46__1)...
        [FBC_GPA] R_GPH__45__RXN
          (CBJ28195__46__1 or CBJ29025__46__1)...

  Organism: CHO
  File: CHO.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 3349
    Species: 3717
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 2809
      Sample IDs:
        - EGV91281__46__1 (label: EGV91281__46__1)
        - EGV91340__46__1 (label: EGV91340__46__1)
        - EGV91370__46__1 (label: EGV91370__46__1)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_GLYCOLATE_REDUCTASE_RXN
          (EGW00407__46__1 or EGW00864__46__1)...
        [FBC_GPA] R_DEOXYADENOSINE_KINASE_RXN
          (EGW00581__46__1 or EGW09957__46__1)...

  Organism: A_aegypti
  File: A_aegypti.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 2573
    Species: 3053
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 4604
      Sample IDs:
        - XP_001647579__46__2 (label: XP_001647579__46__2)
        - XP_001647586__46__2 (label: XP_001647586__46__2)
        - XP_001647648__46__2 (label: XP_001647648__46__2)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_GLYCOLATE_REDUCTASE_RXN
          (XP_001650858__46__1 or XP_001650860__46__1 or XP_021693117__46__1 or XP_021693119__46__1 or XP_0216...
        [FBC_GPA] R_DEOXYADENOSINE_KINASE_RXN
          (XP_001657341__46__1 or XP_001657342__46__1)...

================================================================================
METHOD: pathway_tools
================================================================================

  Organism: E_siliculosus
  File: E_siliculosus.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 2934
    Species: 3159
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_RXN__45__17884
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (CBJ48774.1) or (CBJ3...
        [Notes] R_PYRIMSYN1__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (CBJ30925.1)</p>
    ...

  Organism: CHO
  File: CHO.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 3482
    Species: 3561
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_RXN__45__3341
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (EGW08401.1)</p>
    ...
        [Notes] R_RXN__45__20341
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (EGW13114.1) or (EGV9...

  Organism: A_aegypti
  File: A_aegypti.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 2831
    Species: 2981
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_SERINE__45____45__GLYOXYLATE__45__AMINOTRANSFERASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (XP_001660875.1) or (...
        [Notes] R_RXN__45__12376
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (XP_001654461.1)</p>
...

================================================================================
METHOD: reference
================================================================================

  Organism: E_siliculosus
  File: E_siliculosus.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1977
    Species: 2206
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types Found: ['Notes_contains_gene']
      Examples:
        [Notes] R_RXN__45__11109
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>CATEGORIES: ANNOTATION</p>
    <p>GENE ...
        [Notes] R_RXN__45__12561
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>CATEGORIES: ANNOTATION</p>
    <p>GENE ...

  Organism: CHO
  File: CHO.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 6663
    Species: 4456
    Plugins: ['fbc']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1766
      Sample IDs:
        - G_100751303 (label: 100751303)
        - G_100751305 (label: 100751305)
        - G_100751325 (label: 100751325)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_24_25VITD2Hm
          (100751280 and 100751853 and 100773278)...
        [FBC_GPA] R_24_25VITD3Hm
          (100751280 and 100751853 and 100773278)...

  Organism: A_aegypti
  File: A_aegypti.xml
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 5678
    Species: 4782
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1466
      Sample IDs:
        - G_AAEL014594 (label: G_AAEL014594)
        - G_AAEL002031 (label: G_AAEL002031)
        - G_AAEL008638 (label: G_AAEL008638)
    Gene Association Types Found: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] R_24_25VITD2Hm
          (G_AAEL001960 or G_AAEL006827 or G_AAEL014594 or G_AAEL002005 or G_AAEL002031 or G_AAEL008638)...
        [FBC_GPA] R_24_25VITD3Hm

In [19]:
# Cell 4: Summary table of what we found

summary_data = []

for method, organisms in all_findings.items():
    for organism, findings in organisms.items():
        if "error" not in findings:
            summary_data.append({
                'Method': method,
                'Organism': organism,
                'FBC_Plugin': findings.get('fbc_plugin', False),
                'Num_Gene_Products': findings.get('num_gene_products', 0),
                'Gene_Assoc_Types': ', '.join(findings.get('gene_association_types', [])),
                'Num_Reactions': findings.get('num_reactions', 0),
                'SBML_Level': findings.get('sbml_level', '?'),
                'Plugins': ', '.join(findings.get('plugins', []))
            })

df_summary = pd.DataFrame(summary_data)

print("\n📊 SUMMARY OF ALL MODELS")
print("="*80)
display(df_summary)

print("\n📈 Gene information availability by method:")
display(df_summary.groupby('Method').agg({
    'FBC_Plugin': 'sum',
    'Num_Gene_Products': 'mean',
    'Gene_Assoc_Types': lambda x: len(set(y for y in x if y))
}))

📊 SUMMARY OF ALL MODELS
================================================================================

,Method,Organism,FBC_Plugin,Num_Gene_Products,Gene_Assoc_Types,Num_Reactions,SBML_Level,Plugins
0,carveMe,E_siliculosus,True,786,FBC_GeneProductAssociation,1548,3,fbc
1,carveMe,CHO,True,702,,1163,3,fbc
2,carveMe,A_aegypti,True,649,,1087,3,fbc
3,merlin,E_siliculosus,True,1642,FBC_GeneProductAssociation,3813,3,"fbc, groups"
4,merlin,CHO,True,2807,FBC_GeneProductAssociation,6390,3,"fbc, groups"
5,merlin,A_aegypti,True,4306,FBC_GeneProductAssociation,4820,3,"fbc, groups"
6,modelseed,E_siliculosus,False,0,Notes_contains_gene,1104,2,layout
7,modelseed,CHO,False,0,Notes_contains_gene,1104,2,layout
8,modelseed,A_aegypti,False,0,Notes_contains_gene,1104,2,layout
9,raven_homo,E_siliculosus,True,1141,FBC_GeneProductAssociation,1710,3,"fbc, groups"
10,raven_homo,CHO,True,1990,FBC_GeneProductAssociation,2210,3,"fbc, groups"
11,raven_homo,A_aegypti,True,3452,FBC_GeneProductAssociation,1723,3,"fbc, groups"
12,raven,E_siliculosus,True,1428,FBC_GeneProductAssociation,1322,3,"fbc, groups"
13,raven,CHO,True,2275,FBC_GeneProductAssociation,1756,3,"fbc, groups"
14,raven,A_aegypti,True,3677,FBC_GeneProductAssociation,1365,3,"fbc, groups"
15,AuReMe,E_siliculosus,True,0,Notes_contains_gene,3403,3,fbc
16,AuReMe,CHO,True,0,Notes_contains_gene,6968,3,fbc
17,AuReMe,A_aegypti,True,0,Notes_contains_gene,1851,3,fbc
18,raven_comb,E_siliculosus,True,1700,FBC_GeneProductAssociation,2503,3,"fbc, groups"
19,raven_comb,CHO,True,2809,FBC_GeneProductAssociation,3349,3,"fbc, groups"
20,raven_comb,A_aegypti,True,4604,FBC_GeneProductAssociation,2573,3,"fbc, groups"
21,pathway_tools,E_siliculosus,True,0,Notes_contains_gene,2934,3,fbc
22,pathway_tools,CHO,True,0,Notes_contains_gene,3482,3,fbc
23,pathway_tools,A_aegypti,True,0,Notes_contains_gene,2831,3,fbc
24,reference,E_siliculosus,True,0,Notes_contains_gene,1977,3,fbc
25,reference,CHO,True,1766,FBC_GeneProductAssociation,6663,3,fbc
26,reference,A_aegypti,True,1466,FBC_GeneProductAssociation,5678,3,"fbc, groups"

📈 Gene information availability by method:

               FBC_Plugin  Num_Gene_Products  Gene_Assoc_Types
Method
AuReMe                  3           0.000000                 1
carveMe                 3         712.333333                 1
merlin                  3        2918.333333                 1
modelseed               0           0.000000                 1
pathway_tools           3           0.000000                 1
raven                   3        2460.000000                 1
raven_comb              3        3037.666667                 1
raven_homo              3        2194.333333                 1
reference               3        1077.333333                 2

In [20]:
# Cell 5: Deep dive into a specific problematic model (like AuReMe)

# CHANGE THESE
problem_method = "AuReMe"  # or whatever method has issues
problem_organism = "organism_name"

if problem_method in all_findings and problem_organism in all_findings[problem_method]:
    findings = all_findings[problem_method][problem_organism]
    
    print(f"🔍 DEEP DIVE: {problem_method}/{problem_organism}")
    print("="*80)
    
    # Show everything we found
    for key, value in findings.items():
        print(f"\n{key}:")
        if isinstance(value, list):
            for item in value:
                print(f"  - {item}")
        else:
            print(f"  {value}")
    
    # Now let's look at the RAW XML to see what's really there
    sbml_file = base_path / problem_method / f"{problem_organism}.xml"
    
    print(f"\n\n{'='*80}")
    print("RAW XML INSPECTION (first 5000 chars)")
    print("="*80)
    
    with open(sbml_file, 'r', encoding='utf-8') as f:
        content = f.read(5000)
        print(content)

In [13]:
# Cell 7: Compare gene overlap between methods

comparison_data = []

# Get all unique organisms across methods
all_organisms = set()
for method_data in results.values():
    all_organisms.update(method_data.keys())

# Compare methods pairwise for each organism
for organism in sorted(all_organisms):
    # Collect genes from each method for this organism
    methods_genes = {}
    for method, organisms_dict in results.items():
        if organism in organisms_dict:
            methods_genes[method] = organisms_dict[organism]
    
    # Calculate pairwise intersections between methods
    methods_list = list(methods_genes.keys())
    for i, method1 in enumerate(methods_list):
        for method2 in methods_list[i+1:]:
            genes1 = methods_genes[method1]
            genes2 = methods_genes[method2]
            
            # Set operations for comparison
            intersection = genes1 & genes2
            union = genes1 | genes2
            only_method1 = genes1 - genes2
            only_method2 = genes2 - genes1
            
            # Calculate similarity metrics
            jaccard = len(intersection) / len(union) if len(union) > 0 else 0
            overlap_pct = (len(intersection) / min(len(genes1), len(genes2)) * 100) if min(len(genes1), len(genes2)) > 0 else 0
            
            comparison_data.append({
                'Organism': organism,
                'Method_1': method1,
                'Method_2': method2,
                'Genes_Method_1': len(genes1),
                'Genes_Method_2': len(genes2),
                'Shared_Genes': len(intersection),
                'Only_Method_1': len(only_method1),
                'Only_Method_2': len(only_method2),
                'Jaccard_Index': jaccard,
                'Overlap_Percent': overlap_pct
            })

df_comparison = pd.DataFrame(comparison_data)
df_comparison = df_comparison.sort_values(['Organism', 'Jaccard_Index'], ascending=[True, False])

print("🔬 METHOD COMPARISON")
print("=" * 60)
display(df_comparison)

🔬 METHOD COMPARISON
============================================================

,Organism,Method_1,Method_2,Genes_Method_1,Genes_Method_2,Shared_Genes,Only_Method_1,Only_Method_2,Jaccard_Index,Overlap_Percent
27,A_aegypti,raven,raven_comb,3677,4604,3677,0,927,0.798653,100.000000
23,A_aegypti,raven_homo,raven_comb,3452,4604,3452,0,1152,0.749783,100.000000
21,A_aegypti,raven_homo,raven,3452,3677,2525,927,1152,0.548436,73.146002
0,A_aegypti,carveMe,merlin,649,4306,421,228,3885,0.092854,64.869029
1,A_aegypti,carveMe,modelseed,649,0,0,649,0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
103,E_siliculosus,AuReMe,pathway_tools,0,0,0,0,0,0.000000,0.000000
104,E_siliculosus,AuReMe,reference,0,0,0,0,0,0.000000,0.000000
105,E_siliculosus,raven_comb,pathway_tools,1700,0,0,1700,0,0.000000,0.000000
106,E_siliculosus,raven_comb,reference,1700,0,0,1700,0,0.000000,0.000000
107,E_siliculosus,pathway_tools,reference,0,0,0,0,0,0.000000,0.000000

In [23]:
# Cell 3: Explore ALL models - ORGANIZED BY ORGANISM
from collections import defaultdict
# CHANGE THIS PATH
base_path = Path("models/")

# Store all findings organized by ORGANISM first, then method
all_findings_by_organism = defaultdict(dict)

# First pass: collect all data
for method_folder in base_path.iterdir():
    if not method_folder.is_dir():
        continue
    
    method_name = method_folder.name
    
    for sbml_file in method_folder.glob("*.xml"):
        organism = sbml_file.stem
        findings = explore_sbml_structure(str(sbml_file))
        all_findings_by_organism[organism][method_name] = findings

# Second pass: print organized by organism
for organism in sorted(all_findings_by_organism.keys()):
    print(f"\n{'='*80}")
    print(f"🧬 ORGANISM: {organism}")
    print(f"{'='*80}")
    
    methods_data = all_findings_by_organism[organism]
    
    for method_name, findings in methods_data.items():
        print(f"\n  📁 Method: {method_name}")
        print(f"  {'-'*76}")
        
        # Print key findings
        if "error" in findings:
            print(f"    ❌ {findings['error']}")
            continue
        
        print(f"    SBML Level {findings['sbml_level']}, Version {findings['sbml_version']}")
        print(f"    Reactions: {findings['num_reactions']}, Species: {findings['num_species']}")
        print(f"    Plugins: {findings['plugins']}")
        print(f"    FBC Plugin: {findings['fbc_plugin']}")
        
        if findings.get('num_gene_products', 0) > 0:
            print(f"    ✓ Gene Products (FBC): {findings['num_gene_products']}")
            if findings.get('sample_gene_products'):
                print(f"      Sample Gene IDs:")
                for gp in findings['sample_gene_products'][:3]:
                    print(f"        - ID: {gp['id']}")
                    if gp['label'] != "No label":
                        print(f"          Label: {gp['label']}")
                    if gp['name'] != "No name":
                        print(f"          Name: {gp['name']}")
        else:
            print(f"    ✗ No FBC Gene Products found")
        
        if findings.get('gene_association_types'):
            print(f"    Gene Association Types: {findings['gene_association_types']}")
            if findings.get('sample_associations'):
                print(f"      Examples:")
                for assoc in findings['sample_associations'][:2]:
                    print(f"        [{assoc['type']}] Reaction: {assoc['reaction']}")
                    print(f"          {assoc['content'][:150]}...")
    
    # Summary comparison for this organism
    print(f"\n  {'─'*76}")
    print(f"  📊 Summary for {organism}:")
    has_genes = {}
    for method_name, findings in methods_data.items():
        if "error" not in findings:
            num_genes = findings.get('num_gene_products', 0)
            has_genes[method_name] = num_genes
            gene_types = findings.get('gene_association_types', [])
            status = "✓" if num_genes > 0 or gene_types else "✗"
            print(f"    {status} {method_name}: {num_genes} FBC genes, Types: {gene_types}")
    print(f"  {'─'*76}")

print(f"\n{'='*80}")
print("✓ Exploration complete")

================================================================================
🧬 ORGANISM: A_aegypti
================================================================================

  📁 Method: carveMe
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1087, Species: 790
    Plugins: ['fbc']
    FBC Plugin: True
    ✓ Gene Products (FBC): 649
      Sample Gene IDs:
        - ID: G_XP_001649088_2
          Label: G_XP_001649088_2
          Name: G_XP_001649088_2
        - ID: G_XP_021696045_1
          Label: G_XP_021696045_1
          Name: G_XP_021696045_1
        - ID: G_XP_001662725_1
          Label: G_XP_001662725_1
          Name: G_XP_001662725_1

  📁 Method: merlin
  ----------------------------------------------------------------------------
    SBML Level 3, Version 2
    Reactions: 4820, Species: 4466
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 4306
      Sample Gene IDs:
        - ID: G_XP_021702256_1
          Label: XP_021702256_1
        - ID: G_XP_021698884_1
          Label: XP_021698884_1
        - ID: G_XP_021702715_1
          Label: XP_021702715_1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_R02108__extr
          (XP_001663616_1 or XP_001652172_1 or XP_001653283_2 or XP_001652404_1 or XP_021711527_1 or XP_001653284_2 or XP_001658576_2 or XP_001653282_2 or XP_02...
        [FBC_GPA] Reaction: R_TO0000304_cytmem__cytmem
          (XP_021705410_1 or XP_021705409_1 or XP_021705408_1 or XP_001653426_2 or XP_021705411_1)...

  📁 Method: modelseed
  ----------------------------------------------------------------------------
    SBML Level 2, Version 1
    Reactions: 1104, Species: 1179
    Plugins: ['layout']
    FBC Plugin: False
    ✗ No FBC Gene Products found
    Gene Association Types: ['Notes_contains_gene']
      Examples:
        [Notes] Reaction: R_rxn00001_c0
          <notes>
  <html:p>GENE_ASSOCIATION:Unknown</html:p>
  <html:p>PROTEIN_ASSOCIATION:Unknown</html:p>
</notes>...
        [Notes] Reaction: R_rxn00001_d0
          <notes>
  <html:p>GENE_ASSOCIATION:Unknown</html:p>
  <html:p>PROTEIN_ASSOCIATION:Unknown</html:p>
</notes>...

  📁 Method: raven_homo
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1723, Species: 1897
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 3452
      Sample Gene IDs:
        - ID: XP_021705167__46__1
          Label: XP_021705167__46__1
        - ID: XP_021706998__46__1
          Label: XP_021706998__46__1
        - ID: XP_021706447__46__1
          Label: XP_021706447__46__1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_R00006
          (XP_001660326__46__1 or XP_021712412__46__1)...
        [FBC_GPA] Reaction: R_R00009
          (XP_001663600__46__1 or XP_011493719__46__1)...

  📁 Method: raven
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1365, Species: 1753
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 3677
      Sample Gene IDs:
        - ID: XP_001647579__46__2
          Label: XP_001647579__46__2
        - ID: XP_001647586__46__2
          Label: XP_001647586__46__2
        - ID: XP_001647648__46__2
          Label: XP_001647648__46__2
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_GLYCOLATE__45__REDUCTASE__45__RXN
          (XP_001650858__46__1 or XP_001650860__46__1 or XP_021693117__46__1 or XP_021693119__46__1 or XP_021693120__46__1)...
        [FBC_GPA] Reaction: R_DEOXYADENOSINE__45__KINASE__45__RXN
          (XP_001657341__46__1 or XP_001657342__46__1)...

  📁 Method: AuReMe
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1851, Species: 2294
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types: ['Notes_contains_gene']
      Examples:
        [Notes] Reaction: R_1__45__PHOSPHATIDYLINOSITOL__45__3__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (XP_021700783.1) or (XP_021700784.1) or (XP_021700539.1) or (XP_0217007...
        [Notes] Reaction: R_1__45__PHOSPHATIDYLINOSITOL__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (XP_021695754.1) or (XP_001649005.2) or (XP_021695753.1) or (XP_0217076...

  📁 Method: raven_comb
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 2573, Species: 3053
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 4604
      Sample Gene IDs:
        - ID: XP_001647579__46__2
          Label: XP_001647579__46__2
        - ID: XP_001647586__46__2
          Label: XP_001647586__46__2
        - ID: XP_001647648__46__2
          Label: XP_001647648__46__2
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_GLYCOLATE_REDUCTASE_RXN
          (XP_001650858__46__1 or XP_001650860__46__1 or XP_021693117__46__1 or XP_021693119__46__1 or XP_021693120__46__1)...
        [FBC_GPA] Reaction: R_DEOXYADENOSINE_KINASE_RXN
          (XP_001657341__46__1 or XP_001657342__46__1)...

  📁 Method: pathway_tools
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 2831, Species: 2981
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types: ['Notes_contains_gene']
      Examples:
        [Notes] Reaction: R_SERINE__45____45__GLYOXYLATE__45__AMINOTRANSFERASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (XP_001660875.1) or (XP_021705374.1) or (XP_001656924.2)</p>
    <p>CAT...
        [Notes] Reaction: R_RXN__45__12376
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (XP_001654461.1)</p>
    <p>CATEGORIES: ANNOTATION</p>
    <p>SUBSYSTEM...

  📁 Method: reference
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 5678, Species: 4782
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1466
      Sample Gene IDs:
        - ID: G_AAEL014594
          Label: G_AAEL014594
          Name: AAEL014594
        - ID: G_AAEL002031
          Label: G_AAEL002031
          Name: AAEL002031
        - ID: G_AAEL008638
          Label: G_AAEL008638
          Name: AAEL008638
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_24_25VITD2Hm
          (G_AAEL001960 or G_AAEL006827 or G_AAEL014594 or G_AAEL002005 or G_AAEL002031 or G_AAEL008638)...
        [FBC_GPA] Reaction: R_24_25VITD3Hm
          (G_AAEL001960 or G_AAEL006827 or G_AAEL014594 or G_AAEL002005 or G_AAEL002031 or G_AAEL008638)...

  ────────────────────────────────────────────────────────────────────────────
  📊 Summary for A_aegypti:
    ✓ carveMe: 649 FBC genes, Types: []
    ✓ merlin: 4306 FBC genes, Types: ['FBC_GeneProductAssociation']
    ✓ modelseed: 0 FBC genes, Types: ['Notes_contains_gene']
    ✓ raven_homo: 3452 FBC genes, Types: ['FBC_GeneProductAssociation']
    ✓ raven: 3677 FBC genes, Types: ['FBC_GeneProductAssociation']
    ✓ AuReMe: 0 FBC genes, Types: ['Notes_contains_gene']
    ✓ raven_comb: 4604 FBC genes, Types: ['FBC_GeneProductAssociation']
    ✓ pathway_tools: 0 FBC genes, Types: ['Notes_contains_gene']
    ✓ reference: 1466 FBC genes, Types: ['FBC_GeneProductAssociation']
  ────────────────────────────────────────────────────────────────────────────

================================================================================
🧬 ORGANISM: CHO
================================================================================

  📁 Method: carveMe
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1163, Species: 850
    Plugins: ['fbc']
    FBC Plugin: True
    ✓ Gene Products (FBC): 702
      Sample Gene IDs:
        - ID: G_EGW07470_1
          Label: G_EGW07470_1
          Name: G_EGW07470_1
        - ID: G_EGW07730_1
          Label: G_EGW07730_1
          Name: G_EGW07730_1
        - ID: G_EGW00123_1
          Label: G_EGW00123_1
          Name: G_EGW00123_1

  📁 Method: merlin
  ----------------------------------------------------------------------------
    SBML Level 3, Version 2
    Reactions: 6390, Species: 5584
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 2807
      Sample Gene IDs:
        - ID: G_EGW02227_1
          Label: EGW02227_1
        - ID: G_EGV96904_1
          Label: EGV96904_1
        - ID: G_EGW01634_1
          Label: EGW01634_1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_R02108__extr
          (EGV96608_1 or EGV96609_1)...
        [FBC_GPA] Reaction: R_R11895__nucl
          (EGW13933_1 or EGV99751_1 or EGW05467_1 or EGW04365_1 or EGW08268_1 or EGV92142_1 or EGW01255_1 or EGW08267_1 or EGW11261_1 or EGW04425_1 or EGV93745_...

  📁 Method: modelseed
  ----------------------------------------------------------------------------
    SBML Level 2, Version 1
    Reactions: 1104, Species: 1179
    Plugins: ['layout']
    FBC Plugin: False
    ✗ No FBC Gene Products found
    Gene Association Types: ['Notes_contains_gene']
      Examples:
        [Notes] Reaction: R_rxn00001_c0
          <notes>
  <html:p>GENE_ASSOCIATION:(EGV93776.1 or (EGW03581.1 or EGW02191.1 or EGW14471.1 or EGV93834.1 or EGV99210.1))</html:p>
  <html:p>PROTEIN_ASS...
        [Notes] Reaction: R_rxn00001_d0
          <notes>
  <html:p>GENE_ASSOCIATION:EGV93776.1</html:p>
  <html:p>PROTEIN_ASSOCIATION:EGV93776.1</html:p>
</notes>...

  📁 Method: raven_homo
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 2210, Species: 2288
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1990
      Sample Gene IDs:
        - ID: EGW03289__46__1
          Label: EGW03289__46__1
        - ID: EGW12439__46__1
          Label: EGW12439__46__1
        - ID: EGW15111__46__1
          Label: EGW15111__46__1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_R00006
          EGV95477__46__1...
        [FBC_GPA] Reaction: R_R00009
          EGV94204__46__1...

  📁 Method: raven
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1756, Species: 2127
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 2275
      Sample Gene IDs:
        - ID: EGV91281__46__1
          Label: EGV91281__46__1
        - ID: EGV91340__46__1
          Label: EGV91340__46__1
        - ID: EGV91370__46__1
          Label: EGV91370__46__1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_GLYCOLATE__45__REDUCTASE__45__RXN
          (EGW00407__46__1 or EGW00864__46__1)...
        [FBC_GPA] Reaction: R_DEOXYADENOSINE__45__KINASE__45__RXN
          (EGW00581__46__1 or EGW09957__46__1)...

  📁 Method: AuReMe
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 6968, Species: 6629
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types: ['Notes_contains_gene']
      Examples:
        [Notes] Reaction: R_1__45__PHOSPHATIDYLINOSITOL__45__3__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (EGW11902.1) or (EGV98240.1) or (EGW10318.1) or (EGV98740.1) or (EGW042...
        [Notes] Reaction: R_1__45__PHOSPHATIDYLINOSITOL__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (EGV99292.1) or (EGV94837.1) or (EGW09589.1) or (EGW12600.1)</p>
    <p...

  📁 Method: raven_comb
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 3349, Species: 3717
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 2809
      Sample Gene IDs:
        - ID: EGV91281__46__1
          Label: EGV91281__46__1
        - ID: EGV91340__46__1
          Label: EGV91340__46__1
        - ID: EGV91370__46__1
          Label: EGV91370__46__1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_GLYCOLATE_REDUCTASE_RXN
          (EGW00407__46__1 or EGW00864__46__1)...
        [FBC_GPA] Reaction: R_DEOXYADENOSINE_KINASE_RXN
          (EGW00581__46__1 or EGW09957__46__1)...

  📁 Method: pathway_tools
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 3482, Species: 3561
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types: ['Notes_contains_gene']
      Examples:
        [Notes] Reaction: R_RXN__45__3341
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (EGW08401.1)</p>
    <p>CATEGORIES: ANNOTATION</p>
  </body>
</notes>...
        [Notes] Reaction: R_RXN__45__20341
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (EGW13114.1) or (EGV94125.1)</p>
    <p>CATEGORIES: ANNOTATION</p>
    ...

  📁 Method: reference
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 6663, Species: 4456
    Plugins: ['fbc']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1766
      Sample Gene IDs:
        - ID: G_100751303
          Label: 100751303
          Name: Aldh8a1
        - ID: G_100751305
          Label: 100751305
          Name: Acsm3
        - ID: G_100751325
          Label: 100751325
          Name: LOC100751325
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_24_25VITD2Hm
          (100751280 and 100751853 and 100773278)...
        [FBC_GPA] Reaction: R_24_25VITD3Hm
          (100751280 and 100751853 and 100773278)...

  ────────────────────────────────────────────────────────────────────────────
  📊 Summary for CHO:
    ✓ carveMe: 702 FBC genes, Types: []
    ✓ merlin: 2807 FBC genes, Types: ['FBC_GeneProductAssociation']
    ✓ modelseed: 0 FBC genes, Types: ['Notes_contains_gene']
    ✓ raven_homo: 1990 FBC genes, Types: ['FBC_GeneProductAssociation']
    ✓ raven: 2275 FBC genes, Types: ['FBC_GeneProductAssociation']
    ✓ AuReMe: 0 FBC genes, Types: ['Notes_contains_gene']
    ✓ raven_comb: 2809 FBC genes, Types: ['FBC_GeneProductAssociation']
    ✓ pathway_tools: 0 FBC genes, Types: ['Notes_contains_gene']
    ✓ reference: 1766 FBC genes, Types: ['FBC_GeneProductAssociation']
  ────────────────────────────────────────────────────────────────────────────

================================================================================
🧬 ORGANISM: E_siliculosus
================================================================================

  📁 Method: carveMe
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1548, Species: 1080
    Plugins: ['fbc']
    FBC Plugin: True
    ✓ Gene Products (FBC): 786
      Sample Gene IDs:
        - ID: G_CBJ27061_1
          Label: G_CBJ27061_1
          Name: G_CBJ27061_1
        - ID: G_CBN77946_1
          Label: G_CBN77946_1
          Name: G_CBN77946_1
        - ID: G_CBN76757_1
          Label: G_CBN76757_1
          Name: G_CBN76757_1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_24DECOAR
          G_CBJ27061_1...

  📁 Method: merlin
  ----------------------------------------------------------------------------
    SBML Level 3, Version 2
    Reactions: 3813, Species: 4492
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1642
      Sample Gene IDs:
        - ID: G_Esi_0418_0003
          Label: Esi_0418_0003
        - ID: G_CBN74931_1
          Label: CBN74931_1
        - ID: G_CBN75524_1
          Label: CBN75524_1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_R06945__cytop
          CBJ30233_1...
        [FBC_GPA] Reaction: R_R00562__cytop
          CBN79046_1...

  📁 Method: modelseed
  ----------------------------------------------------------------------------
    SBML Level 2, Version 1
    Reactions: 1104, Species: 1179
    Plugins: ['layout']
    FBC Plugin: False
    ✗ No FBC Gene Products found
    Gene Association Types: ['Notes_contains_gene']
      Examples:
        [Notes] Reaction: R_rxn00001_c0
          <notes>
  <html:p>GENE_ASSOCIATION:((CBN78008.1 or CBN78155.1 or CBJ27682.1) or (CBJ25689.1 or CBN78820.1 or CBN74034.1))</html:p>
  <html:p>PROTEIN_A...
        [Notes] Reaction: R_rxn00001_d0
          <notes>
  <html:p>GENE_ASSOCIATION:(CBN78008.1 or CBN78155.1 or CBJ27682.1)</html:p>
  <html:p>PROTEIN_ASSOCIATION:(CBN78008.1 or CBN78155.1 or CBJ276...

  📁 Method: raven_homo
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1710, Species: 1928
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1141
      Sample Gene IDs:
        - ID: CBJ48774__46__1
          Label: CBJ48774__46__1
        - ID: CBJ30928__46__1
          Label: CBJ30928__46__1
        - ID: CBN78444__46__1
          Label: CBN78444__46__1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_R00009
          CBJ26817__46__1...
        [FBC_GPA] Reaction: R_R00010
          (CBJ29799__46__1 or CBJ33981__46__1)...

  📁 Method: raven
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 1322, Species: 1789
    Plugins: ['fbc', 'groups']
    FBC Plugin: True
    ✓ Gene Products (FBC): 1428
      Sample Gene IDs:
        - ID: CBJ25464__46__1
          Label: CBJ25464__46__1
        - ID: CBJ25471__46__1
          Label: CBJ25471__46__1
        - ID: CBJ25483__46__1
          Label: CBJ25483__46__1
    Gene Association Types: ['FBC_GeneProductAssociation']
      Examples:
        [FBC_GPA] Reaction: R_RXN__45__8042
          (CBJ27057__46__1 or CBJ28883__46__1 or CBJ31710__46__1)...
        [FBC_GPA] Reaction: R_GPH__45__RXN
          (CBJ28195__46__1 or CBJ29025__46__1)...

  📁 Method: AuReMe
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 3403, Species: 3981
    Plugins: ['fbc']
    FBC Plugin: True
    ✗ No FBC Gene Products found
    Gene Association Types: ['Notes_contains_gene']
      Examples:
        [Notes] Reaction: R_1__45__PHOSPHATIDYLINOSITOL__45__3__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (CBJ33367.1) or (CBN77274.1) or (CBN77334.1) or (CBN77270.1) or (CBJ489...
        [Notes] Reaction: R_1__45__PHOSPHATIDYLINOSITOL__45__KINASE__45__RXN
          <notes>
  <body xmlns="http://www.w3.org/1999/xhtml">
    <p>GENE_ASSOCIATION: (CBN79112.1) or (CBN75947.1) or (CBJ26786.1) or (CBN77172.1) or (CBJ278...

  📁 Method: raven_comb
  ----------------------------------------------------------------------------
    SBML Level 3, Version 1
    Reactions: 2503, Species: 3043
    Plugins: ['fbc', 'groups']